# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brysbaert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.CharField(max_length=100, verbose_name='Lemma of word')),
                ('list', models.IntegerField(default=0, verbose_name='List number')),
                ('m', models.FloatField(default=0.0, verbose_name='Concrete m')),
                ('sd', models.FloatField(default=0.0, verbose_name='Concrete sd')),
                ('ratings', models.FloatField(default=0.0, verbose_name='Number_of_ratings')),
                ('responses', models.FloatField(default=0.0, verbose_name='Number_of_N-responses')),
                ('subjects', models.FloatField(default=0.0, verbose_name='Number_of_subjects')),
            ],
        ),
    ]
