# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-18 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_brysbaert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='froglink',
            name='docs',
        ),
        migrations.AddField(
            model_name='froglink',
            name='concr',
            field=models.TextField(blank=True, null=True, verbose_name='Concreteness scores'),
        ),
        migrations.AddField(
            model_name='froglink',
            name='fdocs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doc.FoliaDocs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='froglink',
            name='fullname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Full path of this file'),
        ),
    ]
