# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-28 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0003_auto_20190318_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexisBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0, verbose_name='Number of files')),
            ],
        ),
        migrations.CreateModel(
            name='NexisDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NexisLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name to be used for this file')),
                ('fullname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Full path of this file')),
                ('nmeta', models.TextField(blank=True, null=True, verbose_name='Nexis metadata')),
                ('nbody', models.TextField(blank=True, null=True, verbose_name='Nexis text')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchlinks', to='doc.NexisBatch')),
                ('ndocs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nexisdocuments', to='doc.NexisDocs')),
            ],
        ),
        migrations.AddField(
            model_name='nexisbatch',
            name='ndocs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndocsbatches', to='doc.NexisDocs'),
        ),
    ]
