# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_auto_20210610_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexisdocs',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owner_nexisdocs', to=settings.AUTH_USER_MODEL),
        ),
    ]
