# Generated by Django 2.2 on 2021-11-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_auto_20210610_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.TextField(verbose_name='Multi-word expression')),
                ('lemmas', models.TextField(blank=True, null=True, verbose_name='The lemma parts')),
                ('score', models.FloatField(default=0.0, verbose_name='Concreteness score')),
            ],
        ),
        migrations.CreateModel(
            name='LocTimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(verbose_name='Example text')),
                ('score', models.FloatField(default=0.0, verbose_name='Concreteness score')),
            ],
        ),
    ]
