# Generated by Django 2.2 on 2021-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_expression_loctimeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='score',
            field=models.CharField(default='0.0', max_length=100, verbose_name='Concreteness score'),
        ),
        migrations.AlterField(
            model_name='loctimeinfo',
            name='score',
            field=models.CharField(default='0.0', max_length=100, verbose_name='Concreteness score'),
        ),
    ]
