# Generated by Django 2.2 on 2022-11-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_neologism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.CharField(max_length=100, verbose_name='Lemma of word')),
                ('postag', models.CharField(blank=True, max_length=100, null=True, verbose_name='POS tag')),
                ('m', models.FloatField(default=0.0, verbose_name='Concrete m')),
            ],
        ),
    ]
