# Generated by Django 2.2 on 2022-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_homonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='homonym',
            name='meaning',
            field=models.TextField(blank=True, null=True, verbose_name='Meaning'),
        ),
    ]
