# Generated by Django 2.2 on 2022-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_homonym_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('coordinate', models.CharField(max_length=100, verbose_name='Coordinate')),
                ('tokens', models.TextField(blank=True, null=True, verbose_name='Tokens')),
                ('postags', models.TextField(blank=True, null=True, verbose_name='POS tags')),
            ],
        ),
    ]
