# Generated by Django 2.2 on 2022-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_twittermsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittermsg',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Row'),
        ),
    ]
