# Generated by Django 2.2 on 2023-01-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_twittermsg_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Worddef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.CharField(max_length=100, verbose_name='Lemma of word')),
                ('m', models.FloatField(default=0.0, verbose_name='Concrete m')),
                ('postag', models.CharField(blank=True, max_length=100, null=True, verbose_name='POS tag')),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordlist_worddefs', to='doc.Wordlist')),
            ],
        ),
    ]
