# Generated by Django 2.2 on 2023-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0015_auto_20230116_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='frogged',
            field=models.TextField(blank=True, null=True, verbose_name='Lemma parts by FROG'),
        ),
    ]
