# Generated by Django 2.2 on 2023-03-09 14:34

import cesar.doc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0016_expression_frogged'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='sheet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Worksheet'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=cesar.doc.models.wordlist_path, verbose_name='Excel file'),
        ),
    ]
