# Generated by Django 2.2 on 2023-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0017_auto_20230309_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='loctimeinfo',
            name='infotype',
            field=models.CharField(default='time', max_length=100, verbose_name='Information type'),
        ),
    ]
