# Generated by Django 2.2 on 2023-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0018_loctimeinfo_infotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='froglink',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Overall score'),
        ),
    ]
