# Generated by Django 2.2 on 2023-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0019_froglink_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='froglink',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Size of text (words)'),
        ),
    ]
