# Generated by Django 2.2 on 2023-09-21 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0022_auto_20230914_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Genre name')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Overall score')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Size of text (words)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='froglink',
            name='fgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_docs', to='doc.Genre'),
        ),
    ]
