# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-31 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('home', models.CharField(max_length=200, verbose_name='Home page part')),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='Remove at')),
                ('msg', models.TextField(verbose_name='Message')),
                ('consent', models.TextField(blank=True, null=True, verbose_name='Informed consent')),
                ('status', models.CharField(choices=[('0', '-'), ('1', 'N/A')], max_length=5, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=100)),
                ('dutch_name', models.CharField(max_length=100)),
                ('abbr', models.CharField(default='-', max_length=20)),
                ('machine_value', models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.')),
            ],
            options={
                'ordering': ['field', 'machine_value'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptcpid', models.CharField(max_length=200, verbose_name='Survey participant ID')),
                ('age', models.IntegerField(verbose_name='Age (number)')),
                ('gender', models.CharField(choices=[('0', '-'), ('1', 'N/A')], max_length=5, verbose_name='Gender')),
                ('engfirst', models.CharField(choices=[('0', '-'), ('1', 'N/A')], max_length=5, verbose_name='English L1')),
                ('lngfirst', models.CharField(blank=True, max_length=200, null=True, verbose_name='First language')),
                ('lngother', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other languages')),
                ('edu', models.CharField(choices=[('0', '-'), ('1', 'N/A')], max_length=5, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answers')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingo.Experiment')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingo.Participant')),
            ],
        ),
    ]
