# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(choices=[('ext', 'Extinct'), ('val', 'Valid')], max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='edu',
            field=models.CharField(choices=[('g1', '12th grade or less'), ('g4', "Associate's degree"), ('g5', "Bachelor's degree"), ('g8', 'Doctorate (PhD or EdD)'), ('g2', 'High school diploma or GED'), ('g6', "Master's degree"), ('g7', 'Professional degree (e.g. MD or JD)'), ('f3', 'Some college but no degree')], max_length=5, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='engfirst',
            field=models.CharField(choices=[('n', 'No'), ('y', 'Yes')], max_length=5, verbose_name='English L1'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('o', 'Other')], max_length=5, verbose_name='Gender'),
        ),
    ]
