# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0002_auto_20190801_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qmeta', models.TextField(blank=True, default='', verbose_name='Question metadata')),
                ('qtext', models.TextField(blank=True, default='', verbose_name='Question data')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingo.Experiment')),
            ],
        ),
    ]
