# Generated by Django 2.0.4 on 2019-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0004_auto_20190826_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='ptcpfields',
            field=models.TextField(blank=True, default='[]', verbose_name='Participant fields'),
        ),
        migrations.AddField(
            model_name='participant',
            name='eduother',
            field=models.TextField(blank=True, default='', verbose_name='Other education'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='edu',
            field=models.CharField(blank=True, choices=[('g1', '12th grade or less'), ('g4', "Associate's degree"), ('g3', 'College with degree'), ('g2', 'High school diploma or GED'), ('g7', 'Other (specify)'), ('g5', 'Technical college'), ('g6', 'University or higher')], default='', max_length=5, verbose_name='Education'),
        ),
    ]
