# Generated by Django 2.0.4 on 2019-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0005_auto_20190903_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdata',
            name='qsuggest',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Suggested topic'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], default='', max_length=5, verbose_name='Gender'),
        ),
    ]
