# Generated by Django 2.0.4 on 2019-09-05 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0006_auto_20190903_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('2_f', 'Female'), ('1_m', 'Male'), ('3_o', 'Other')], default='', max_length=5, verbose_name='Gender'),
        ),
    ]
