# Generated by Django 2.0.4 on 2019-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0009_auto_20190909_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdata',
            name='include',
            field=models.CharField(blank=True, choices=[('n', 'No'), ('y', 'Yes')], default='n', max_length=5, verbose_name='Include text'),
        ),
    ]
