# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-16 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0011_participant_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qdata',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_qdatas', to='lingo.Experiment'),
        ),
    ]
