# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0013_experiment_metafields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='home',
            field=models.CharField(default='tcpf', max_length=200, verbose_name='Home page part'),
        ),
    ]
