# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0014_auto_20200116_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='teaches',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Teaches'),
        ),
    ]
