# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingo', '0017_experiment_showendbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_responses', to='lingo.Experiment'),
        ),
        migrations.AlterField(
            model_name='response',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_responses', to='lingo.Participant'),
        ),
    ]
