# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsetname',
            name='descr',
            field=models.TextField(default='SPECIFY', verbose_name='What kind of constituent does this variable target?'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='eth',
            field=models.CharField(choices=[('3', 'che'), ('0', 'eng'), ('1', 'lbe'), ('2', 'nld')], help_text='Sorry, no help available for corpus.ethnologue', max_length=5, verbose_name='Ethnologue 3-letter code of the text langauge'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='lng',
            field=models.CharField(choices=[('3', 'che_lat'), ('0', 'eng_hist'), ('1', 'lak_cyr'), ('2', 'nld')], help_text='Sorry, no help available for corpus.language', max_length=5, verbose_name='Language of the texts'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='status',
            field=models.CharField(choices=[('0', 'hidden'), ('1', 'public')], help_text='Sorry, no help available for corpus.status', max_length=5, verbose_name="The status (e.g. 'hidden')"),
        ),
        migrations.AlterField(
            model_name='download',
            name='format',
            field=models.CharField(choices=[('1', 'folia'), ('0', 'psdx')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='loc',
            field=models.CharField(choices=[('0', 'header'), ('1', 'mdi')], help_text='Sorry, no help available for variable.loc', max_length=5, verbose_name='Type of this variable'),
        ),
        migrations.AlterField(
            model_name='variablename',
            name='type',
            field=models.CharField(choices=[('1', 'int'), ('0', 'txt')], help_text='Sorry, no help available for variable.type', max_length=5, verbose_name='Type of this variable'),
        ),
    ]
