# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20170301_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='loc',
            field=models.CharField(choices=[('0', 'header'), ('1', 'mdi')], help_text='Sorry, no help available for variable.loc', max_length=5, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.TextField(verbose_name='Xquery definition'),
        ),
    ]
