# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20170301_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metavar',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='This metavar is hidden (?)'),
        ),
    ]
