# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20170301_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsetNameTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.CharField(help_text='Sorry, no help available for language', max_length=5, verbose_name='Language of the texts')),
                ('descr', models.TextField(default='SPECIFY', verbose_name='What kind of constituent does this variable target?')),
                ('tagsetname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.TagsetName')),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='descr',
            field=models.TextField(default='(Put your description here)', verbose_name='Full name of this part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='dir',
            field=models.CharField(default='/', max_length=200, verbose_name='Sub directory of this part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name of this part'),
        ),
    ]
