# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_auto_20170301_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TITLE', max_length=200, verbose_name='Name of the constituent')),
                ('eng', models.TextField(default='SPECIFY', verbose_name='Constituent description (English)')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituentNameTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.CharField(choices=[('0', 'eng'), ('1', 'nld'), ('2', 'rus')], help_text='Sorry, no help available for language', max_length=5, verbose_name='Language')),
                ('descr', models.TextField(default='SPECIFY', verbose_name='Constituent description (in this language)')),
                ('constituent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Constituent')),
            ],
        ),
        migrations.RemoveField(
            model_name='tagsetnametrans',
            name='tagsetname',
        ),
        migrations.RemoveField(
            model_name='tagset',
            name='title',
        ),
        migrations.AlterField(
            model_name='tagset',
            name='definition',
            field=models.CharField(max_length=200, verbose_name='Xquery for the constituent'),
        ),
        migrations.DeleteModel(
            name='TagsetName',
        ),
        migrations.DeleteModel(
            name='TagsetNameTrans',
        ),
        migrations.AddField(
            model_name='tagset',
            name='constituent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='browser.Constituent'),
        ),
    ]
