# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20170301_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status of synchronization')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Error message')),
            ],
        ),
    ]
