# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='count',
            field=models.TextField(default='{}', verbose_name='Count details'),
        ),
    ]
