# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0009_auto_20170316_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200, verbose_name='Name of the text file')),
                ('format', models.CharField(choices=[('1', 'folia'), ('0', 'psdx')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='Format for this corpus (part)')),
                ('metaFile', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the metadata file')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title of this text')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Part')),
            ],
        ),
    ]
