# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_text_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('sent', models.CharField(max_length=200, verbose_name='Sentence')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='browser.Text')),
            ],
        ),
    ]
