# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0013_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoice',
            name='abbr',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='constituentnametrans',
            name='lng',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for language', max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='eth',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for corpus.ethnologue', max_length=5, verbose_name='Ethnologue 3-letter code of the text langauge'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='lng',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for corpus.language', max_length=5, verbose_name='Language of the texts'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='status',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for corpus.status', max_length=5, verbose_name="The status (e.g. 'hidden')"),
        ),
        migrations.AlterField(
            model_name='download',
            name='format',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
        migrations.AlterField(
            model_name='text',
            name='format',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='loc',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for variable.loc', max_length=5, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='variablename',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for variable.type', max_length=5, verbose_name='Type of this variable'),
        ),
    ]
