# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0016_auto_20171127_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.CharField(default='', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.CharField(default='', max_length=255, verbose_name='User'),
        ),
    ]
