# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0017_auto_20180201_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='words',
            field=models.IntegerField(default=0, verbose_name='Number of words'),
        ),
    ]
