# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_text_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_texts', to='browser.Part'),
        ),
    ]
