# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0019_auto_20180326_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='lng',
            field=models.CharField(choices=[('3', 'che_lat'), ('0', 'eng_hist'), ('4', 'eng_penta'), ('5', 'eng_sla'), ('1', 'lak_cyr'), ('2', 'nld')], help_text='Sorry, no help available for corpus.language', max_length=5, verbose_name='Language of the texts'),
        ),
        migrations.AlterField(
            model_name='part',
            name='dir',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sub directory of this part'),
        ),
    ]
