# Generated by Django 2.0.4 on 2019-08-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0021_auto_20181119_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='metavar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='browser.Metavar'),
        ),
    ]
