# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0022_auto_20190828_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='metavar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.Metavar'),
        ),
    ]
