# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-16 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0023_auto_20190910_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='eth',
            field=models.CharField(choices=[('3', 'che'), ('0', 'eng'), ('4', 'grc'), ('5', 'heb'), ('1', 'lbe'), ('2', 'nld')], help_text='Sorry, no help available for corpus.ethnologue', max_length=5, verbose_name='Ethnologue 3-letter code of the text langauge'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='lng',
            field=models.CharField(choices=[('3', 'che_lat'), ('0', 'eng_hist'), ('4', 'eng_penta'), ('5', 'eng_sla'), ('7', 'grk_nt'), ('8', 'heb_ot'), ('1', 'lak_cyr'), ('2', 'nld'), ('6', 'nld_hist')], help_text='Sorry, no help available for corpus.language', max_length=5, verbose_name='Language of the texts'),
        ),
    ]
