# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0025_auto_20210318_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituentnametrans',
            name='constituent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituent_translations', to='browser.Constituent'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='metavar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metavar_corpora', to='browser.Metavar'),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='metavar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metavar_groupings', to='browser.Metavar'),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_groupings', to='browser.GroupingName'),
        ),
        migrations.AlterField(
            model_name='part',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_parts', to='browser.Corpus'),
        ),
        migrations.AlterField(
            model_name='part',
            name='metavar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metavar_parts', to='browser.Metavar'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='constituent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='constituent_tagsets', to='browser.Constituent'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='metavar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metavar_tagsets', to='browser.Metavar'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='metavar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metavar_variables', to='browser.Metavar'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_variables', to='browser.VariableName'),
        ),
    ]
