# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browser', '0013_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentId', models.CharField(max_length=200, verbose_name='Sentence identifier')),
                ('constId', models.CharField(max_length=200, verbose_name='Constituent identifier')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFeatName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of this feature')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ResultFeatName')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crpName', models.CharField(max_length=200, verbose_name='The Corpus Research Project that produced the results')),
                ('created', models.CharField(max_length=200, verbose_name='Date created')),
                ('qc', models.IntegerField(verbose_name='QC line number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes on the results')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Part')),
            ],
        ),
        migrations.CreateModel(
            name='ResultText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ResultSet')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Text')),
            ],
        ),
        migrations.AddField(
            model_name='resultfeatname',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ResultSet'),
        ),
        migrations.AddField(
            model_name='result',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ResultText'),
        ),
    ]
