# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-21 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='Remove at')),
                ('msg', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('ext', 'Extinct'), ('val', 'Valid')], help_text='Sorry, no help available for view.status', max_length=5, verbose_name='Status')),
            ],
        ),
    ]
