# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
