# Generated by Django 2.0.4 on 2019-08-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_newsitem_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.ResultText'),
        ),
        migrations.AlterField(
            model_name='resultfeatname',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.ResultSet'),
        ),
        migrations.AlterField(
            model_name='resultfeature',
            name='ftname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.ResultFeatName'),
        ),
        migrations.AlterField(
            model_name='resultset',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='browser.Part'),
        ),
        migrations.AlterField(
            model_name='resulttext',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.ResultSet'),
        ),
        migrations.AlterField(
            model_name='resulttext',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='browser.Text'),
        ),
    ]
