# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20190910_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_results', to='viewer.ResultText'),
        ),
        migrations.AlterField(
            model_name='resultfeatname',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_resultfeatnames', to='viewer.ResultSet'),
        ),
        migrations.AlterField(
            model_name='resultfeature',
            name='ftname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftname_resultfeatures', to='viewer.ResultFeatName'),
        ),
        migrations.AlterField(
            model_name='resultset',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_resultsets', to='browser.Part'),
        ),
        migrations.AlterField(
            model_name='resulttext',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_resulttexts', to='viewer.ResultSet'),
        ),
        migrations.AlterField(
            model_name='resulttext',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_resulttexts', to='browser.Text'),
        ),
    ]
