# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsghandle',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
