# Generated by Django 2.2.28 on 2024-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsg', '0002_tsghandle_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsghandle',
            name='status',
            field=models.CharField(default='ini', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tsghandle',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Handle URL'),
        ),
    ]
