# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of this search construction')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructionvariables', to='seeker.Construction')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='leeg', max_length=200, verbose_name='Name of this gateway option')),
                ('description', models.TextField(blank=True, verbose_name='Description for this option')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Research project name')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('targetType', models.CharField(choices=[('0', '----'), ('w', 'Word(s)'), ('c', 'Constituent(s)')], max_length=5, verbose_name='Main element type')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeker.Gateway')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of this search item')),
                ('function', models.CharField(help_text='Sorry, no help available for search.function', max_length=5, verbose_name='Format for this corpus (part)')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('operator', models.CharField(help_text='Sorry, no help available for search.operator', max_length=5, verbose_name='Operator')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchitems', to='seeker.Construction')),
            ],
        ),
        migrations.CreateModel(
            name='SearchMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(help_text='Sorry, no help available for search.function', max_length=5, verbose_name='Format for this corpus (part)')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('operator', models.CharField(help_text='Sorry, no help available for search.operator', max_length=5, verbose_name='Operator')),
            ],
        ),
        migrations.CreateModel(
            name='ShareGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(help_text='Sorry, no help available for search.permission', max_length=5, verbose_name='Permissions')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharegroups', to='seeker.Research')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of this variable')),
                ('description', models.TextField(verbose_name='Description of this variable')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seeker.Variable')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
            bases=('seeker.variable',),
        ),
        migrations.AddField(
            model_name='variable',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatewayvariables', to='seeker.Gateway'),
        ),
        migrations.AddField(
            model_name='constructionvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variablenames', to='seeker.Variable'),
        ),
        migrations.AddField(
            model_name='construction',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='seeker.Gateway'),
        ),
        migrations.AddField(
            model_name='construction',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.SearchMain'),
        ),
    ]
