# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionvariable',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
    ]
