# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_auto_20170630_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarDef',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seeker.Variable')),
            ],
            bases=('seeker.variable',),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variablenames', to='seeker.VarDef'),
        ),
    ]
