# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_auto_20170703_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionvariable',
            name='svalue',
            field=models.TextField(blank=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='type',
            field=models.CharField(choices=[('1', 'Calculate'), ('0', 'Fixed value')], help_text='Sorry, no help available for search.variabletype', max_length=5, verbose_name='Variable type'),
        ),
    ]
