# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_auto_20170703_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Descriptive name')),
                ('text', models.CharField(max_length=200, verbose_name='Preceding text')),
                ('argval', models.TextField(blank=True, default='[]', verbose_name='JSON value')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Short function name')),
                ('title', models.CharField(max_length=200, verbose_name='Function title')),
                ('argnum', models.IntegerField(default=1, verbose_name='Number of arguments')),
                ('output', models.TextField(blank=True, default='[]', verbose_name='JSON value')),
            ],
        ),
        migrations.AddField(
            model_name='argument',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='seeker.Function'),
        ),
        migrations.AddField(
            model_name='constructionvariable',
            name='calculate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.Function'),
        ),
    ]
