# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0006_auto_20170705_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Preceding text'),
        ),
    ]
