# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0007_auto_20170705_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Argument',
            new_name='ArgumentDef',
        ),
        migrations.RenameModel(
            old_name='Function',
            new_name='FunctionDef',
        ),
    ]
