# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0008_auto_20170706_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argtype', models.CharField(help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type')),
                ('argval', models.TextField(blank=True, default='[]', verbose_name='JSON value')),
                ('argumentdef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.ArgumentDef')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True, default='[]', verbose_name='JSON value')),
            ],
        ),
        migrations.RemoveField(
            model_name='constructionvariable',
            name='calculate',
        ),
        migrations.RemoveField(
            model_name='functiondef',
            name='output',
        ),
        migrations.AddField(
            model_name='constructionvariable',
            name='gvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.GlobalVariable'),
        ),
        migrations.AddField(
            model_name='function',
            name='functiondef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.FunctionDef'),
        ),
        migrations.AddField(
            model_name='argument',
            name='cvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.ConstructionVariable'),
        ),
        migrations.AddField(
            model_name='argument',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.Function'),
        ),
        migrations.AddField(
            model_name='argument',
            name='gvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.GlobalVariable'),
        ),
        migrations.AddField(
            model_name='constructionvariable',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.Function'),
        ),
    ]
