# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0011_constructionvariable_functiondef'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentdef',
            name='argtype',
            field=models.CharField(choices=[('2', 'Construction variable'), ('0', 'Fixed value'), ('3', 'Function output'), ('1', 'Global variable')], default=0, help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='argumentdef',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='argtype',
            field=models.CharField(choices=[('2', 'Construction variable'), ('0', 'Fixed value'), ('3', 'Function output'), ('1', 'Global variable')], help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type'),
        ),
    ]
