# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0012_auto_20170731_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.FunctionDef'),
        ),
    ]
