# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0013_argument_functiondef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='argtype',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type'),
        ),
        migrations.AlterField(
            model_name='argumentdef',
            name='argtype',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.variabletype', max_length=5, verbose_name='Variable type'),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='function',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.function', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='operator',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.operator', max_length=5, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='searchmain',
            name='function',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.function', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
        migrations.AlterField(
            model_name='searchmain',
            name='operator',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.operator', max_length=5, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='permission',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], help_text='Sorry, no help available for search.permission', max_length=5, verbose_name='Permissions'),
        ),
    ]
