# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0016_auto_20170802_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='gateway',
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='gateway',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='globalvariables', to='seeker.Gateway'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vardef',
            name='gateway',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='definitionvariables', to='seeker.Gateway'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='argument',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functionarguments', to='seeker.Function'),
        ),
    ]
