# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0020_auto_20170823_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='cvar',
        ),
        migrations.AddField(
            model_name='condition',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variablecondition', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condtype',
            field=models.CharField(choices=[('cvar', 'Construction variable'), ('func', 'Function')], help_text='Sorry, no help available for search.condtype', max_length=5, verbose_name='Condition type'),
        ),
    ]
