# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0023_auto_20170831_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.Function'),
        ),
    ]
