# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0025_auto_20170831_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='rootcond',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='functioncondroot', to='seeker.Condition'),
            preserve_default=False,
        ),
    ]
