# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0026_function_rootcond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functionroot', to='seeker.ConstructionVariable'),
        ),
        migrations.AlterField(
            model_name='function',
            name='rootcond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functioncondroot', to='seeker.Condition'),
        ),
    ]
