# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0027_auto_20170831_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='research',
            name='saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
