# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0028_auto_20170902_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
