# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0015_auto_20170802_1639'),
        ('seeker', '0030_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc', models.IntegerField(default=1, verbose_name='QC number')),
                ('count', models.IntegerField(default=0, verbose_name='Number of hits')),
            ],
        ),
        migrations.CreateModel(
            name='Qsubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('count', models.IntegerField(default=0, verbose_name='Number of hits')),
                ('qcline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsubcats', to='seeker.QCline')),
            ],
        ),
        migrations.CreateModel(
            name='Qsubinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Hits')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsubinfos', to='seeker.Qsubcat')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Quantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Number of files')),
                ('searchTime', models.IntegerField(default=0, verbose_name='Search time (ms)')),
                ('qcNum', models.IntegerField(default=1, verbose_name='Number of query lines')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.Basket')),
            ],
        ),
        migrations.AddField(
            model_name='qcline',
            name='quantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qclines', to='seeker.Quantor'),
        ),
    ]
