# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0031_auto_20171101_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kwic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc', models.IntegerField(default=1, verbose_name='QC number')),
                ('textcount', models.IntegerField(default=0, verbose_name='Number of texts')),
                ('hitcount', models.IntegerField(default=0, verbose_name='Number of hits')),
                ('features', models.TextField(default='[]', verbose_name='Features')),
                ('resultKey', models.TextField(blank=True, null=True, verbose_name='Result key')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwiclines', to='seeker.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='KwicFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Database field')),
                ('operator', models.CharField(max_length=5, verbose_name='Filter operator')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('kwic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwicfilters', to='seeker.Kwic')),
            ],
        ),
        migrations.CreateModel(
            name='KwicResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resId', models.IntegerField(verbose_name='Result identifier')),
                ('result', models.TextField(verbose_name='JSON details')),
                ('kwic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwicresults', to='seeker.Kwic')),
            ],
        ),
    ]
