# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0032_kwic_kwicfilter_kwicresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
