# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0033_condition_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('-', 'folia'), ('-', 'psdx')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='XML format')),
                ('xquery', models.TextField(blank=True, default='(: Xquery code for function :)', null=True, verbose_name='Xquery code')),
                ('functiondef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functioncodings', to='seeker.FunctionDef')),
            ],
        ),
    ]
