# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0034_functioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='format',
            field=models.CharField(choices=[('folia', 'folia'), ('psdx', 'psdx')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='XML format'),
        ),
        migrations.AlterField(
            model_name='functioncode',
            name='format',
            field=models.CharField(choices=[('folia', 'folia'), ('psdx', 'psdx')], help_text='Sorry, no help available for corpus.format', max_length=5, verbose_name='XML format'),
        ),
    ]
