# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0035_auto_20171201_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='errors',
            field=models.TextField(default='', verbose_name='Errors'),
        ),
    ]
