# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0036_gateway_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='include',
            field=models.CharField(choices=[('false', 'no'), ('true', 'yes')], default='true', help_text='Sorry, no help available for search.include', max_length=5, verbose_name='Include'),
        ),
    ]
