# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0037_condition_include'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('feattype', models.CharField(help_text='Sorry, no help available for search.feattype', max_length=5, verbose_name='Feature type')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('include', models.CharField(choices=[('false', 'no'), ('true', 'yes')], default='true', help_text='Sorry, no help available for search.include', max_length=5, verbose_name='Include')),
                ('function', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.Function')),
                ('functiondef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functiondeffeature', to='seeker.FunctionDef')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='seeker.Gateway')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variablefeature', to='seeker.VarDef')),
            ],
        ),
        migrations.AlterField(
            model_name='kwicfilter',
            name='operator',
            field=models.CharField(choices=[('and', 'and'), ('andnot', 'and not'), ('first', 'first')], max_length=5, verbose_name='Filter operator'),
        ),
    ]
