# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0038_auto_20171204_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='rootfeat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functionfeatroot', to='seeker.Feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feattype',
            field=models.CharField(choices=[('dvar', 'Data-dependant variable'), ('func', 'Function')], help_text='Sorry, no help available for search.feattype', max_length=5, verbose_name='Feature type'),
        ),
    ]
