# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0039_auto_20171205_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='line',
            field=models.IntegerField(default=0, verbose_name='Line number'),
        ),
    ]
