# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0041_auto_20180209_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argument',
            name='axis',
        ),
        migrations.AddField(
            model_name='relation',
            name='type',
            field=models.CharField(choices=[('cond', 'Conditional relation'), ('axis', 'Hierarchical relation'), ('const', 'Related constituent')], default='axis', help_text='Sorry, no help available for search.relationtype', max_length=5, verbose_name='Relation type'),
        ),
        migrations.DeleteModel(
            name='Axis',
        ),
    ]
