# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0042_auto_20180212_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argument',
            old_name='relation',
            new_name='raxis',
        ),
        migrations.AlterField(
            model_name='argument',
            name='argtype',
            field=models.CharField(choices=[('cnst', 'Constituent'), ('cvar', 'Construction variable'), ('dvar', 'Data-dependant variable'), ('fixed', 'Fixed value'), ('func', 'Function output'), ('gvar', 'Global variable'), ('raxis', 'Relation - axis'), ('rcond', 'Relation - condition'), ('rcnst', 'Relation - constituent'), ('hit', 'Search hit')], help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type'),
        ),
        migrations.AlterField(
            model_name='argumentdef',
            name='argtype',
            field=models.CharField(choices=[('cnst', 'Constituent'), ('cvar', 'Construction variable'), ('dvar', 'Data-dependant variable'), ('fixed', 'Fixed value'), ('func', 'Function output'), ('gvar', 'Global variable'), ('raxis', 'Relation - axis'), ('rcond', 'Relation - condition'), ('rcnst', 'Relation - constituent'), ('hit', 'Search hit')], help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Variable type'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.CharField(choices=[('axis', 'Axis relation'), ('cond', 'Conditional relation'), ('const', 'Related constituent')], default='axis', help_text='Sorry, no help available for search.relationtype', max_length=5, verbose_name='Relation type'),
        ),
    ]
