# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0043_auto_20180212_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='rcond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg_rcond', to='seeker.Relation'),
        ),
        migrations.AddField(
            model_name='argument',
            name='rconst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg_rconst', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='raxis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg_raxis', to='seeker.Relation'),
        ),
    ]
