# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0044_auto_20180212_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentdef',
            name='obltype',
            field=models.CharField(blank=True, choices=[('bool', 'Boolean'), ('cnst', 'Constituent'), ('int', 'Integer'), ('str', 'String')], help_text='Sorry, no help available for search.type', max_length=5, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='argumentdef',
            name='argtype',
            field=models.CharField(choices=[('cnst', 'Constituent'), ('cvar', 'Construction variable'), ('dvar', 'Data-dependant variable'), ('fixed', 'Fixed value'), ('func', 'Function output'), ('gvar', 'Global variable'), ('raxis', 'Relation - axis'), ('rcond', 'Relation - condition'), ('rcnst', 'Relation - constituent'), ('hit', 'Search hit')], help_text='Sorry, no help available for search.argtype', max_length=5, verbose_name='Default variable type'),
        ),
        migrations.AlterField(
            model_name='argumentdef',
            name='hasoutputtype',
            field=models.BooleanField(default=False, verbose_name='Equals outputtype'),
        ),
    ]
