# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0045_auto_20180214_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentdef',
            name='obltype',
            field=models.CharField(blank=True, choices=[('raxis', 'Axis'), ('bool', 'Boolean'), ('cnst', 'Constituent'), ('clist', 'Constituent(s)'), ('int', 'Integer'), ('rcond', 'RelatCond'), ('str', 'String')], help_text='Sorry, no help available for search.type', max_length=5, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='function',
            name='type',
            field=models.CharField(blank=True, choices=[('6', 'Axis'), ('2', 'Boolean'), ('3', 'Constituent'), ('4', 'Constituent(s)'), ('1', 'Integer'), ('5', 'RelatCond'), ('0', 'String')], help_text='Sorry, no help available for search.type', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='functiondef',
            name='type',
            field=models.CharField(blank=True, choices=[('6', 'Axis'), ('2', 'Boolean'), ('3', 'Constituent'), ('4', 'Constituent(s)'), ('1', 'Integer'), ('5', 'RelatCond'), ('0', 'String')], help_text='Sorry, no help available for search.type', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(blank=True, choices=[('6', 'Axis'), ('2', 'Boolean'), ('3', 'Constituent'), ('4', 'Constituent(s)'), ('1', 'Integer'), ('5', 'RelatCond'), ('0', 'String')], help_text='Sorry, no help available for search.type', max_length=5, verbose_name='Type'),
        ),
    ]
