# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0046_auto_20180215_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='status',
            field=models.TextField(default='{}', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='constructionvariable',
            name='status',
            field=models.TextField(default='{}', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.TextField(default='{}', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='function',
            name='status',
            field=models.TextField(default='{}', verbose_name='Status'),
        ),
    ]
