# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0047_auto_20180219_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='options',
            field=models.TextField(blank=True, verbose_name='Search options'),
        ),
    ]
