# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0050_auto_20180326_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmain',
            name='exclude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='function',
            field=models.CharField(choices=[('1', 'const-group'), ('0', 'word-group')], help_text='Sorry, no help available for search.function', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
        migrations.AlterField(
            model_name='searchmain',
            name='function',
            field=models.CharField(choices=[('1', 'const-group'), ('0', 'word-group')], help_text='Sorry, no help available for search.function', max_length=5, verbose_name='Format for this corpus (part)'),
        ),
    ]
