# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0051_auto_20180523_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentdef',
            name='argval',
            field=models.TextField(blank=True, default='[]', verbose_name='(Default value)'),
        ),
    ]
