# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0052_auto_20180605_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condtype',
            field=models.CharField(choices=[('dvar', 'Data-dependant variable'), ('func', 'Function'), ('json', 'Upload JSON')], help_text='Sorry, no help available for search.condtype', max_length=5, verbose_name='Condition type'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='type',
            field=models.CharField(choices=[('calc', 'Calculate'), ('fixed', 'Fixed value'), ('gvar', 'Global variable'), ('json', 'Upload JSON')], help_text='Sorry, no help available for search.variabletype', max_length=5, verbose_name='Variable type'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feattype',
            field=models.CharField(choices=[('dvar', 'Data-dependant variable'), ('func', 'Function'), ('json', 'Upload JSON')], help_text='Sorry, no help available for search.feattype', max_length=5, verbose_name='Feature type'),
        ),
    ]
