# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-25 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seeker', '0053_auto_20180621_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Research project group')),
                ('description', models.TextField(default='-', verbose_name='Description')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentgroup', to='seeker.ResGroup')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childresearch', to='seeker.ResGroup'),
        ),
    ]
