# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0055_auto_20181119_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmain',
            name='cql',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cql'),
        ),
        migrations.AddField(
            model_name='searchmain',
            name='related',
            field=models.TextField(blank=True, null=True, verbose_name='Related constituent(s)'),
        ),
    ]
