# Generated by Django 2.0.4 on 2019-08-28 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0056_auto_20190129_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='argumentdef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.ArgumentDef'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='cvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.ConstructionVariable'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='dvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functionarguments', to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='gvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.GlobalVariable'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='raxis',
            field=models.ForeignKey(limit_choices_to={'type': 'axis'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arg_raxis', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='rcond',
            field=models.ForeignKey(limit_choices_to={'type': 'cond'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arg_rcond', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='rconst',
            field=models.ForeignKey(limit_choices_to={'type': 'const'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arg_rconst', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argumentdef',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arguments', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='browser.Part'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='baskets', to='seeker.Research'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functiondefcondition', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conditions', to='seeker.Gateway'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='variablecondition', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructions', to='seeker.Gateway'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.SearchMain'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructionvariables', to='seeker.Construction'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='gvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.GlobalVariable'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variablenames', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functiondeffeature', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='features', to='seeker.Gateway'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='variablefeature', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='function',
            name='functiondef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='function',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functionparent', to='seeker.Argument'),
        ),
        migrations.AlterField(
            model_name='function',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functionroot', to='seeker.ConstructionVariable'),
        ),
        migrations.AlterField(
            model_name='function',
            name='rootcond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functioncondroot', to='seeker.Condition'),
        ),
        migrations.AlterField(
            model_name='function',
            name='rootfeat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='functionfeatroot', to='seeker.Feature'),
        ),
        migrations.AlterField(
            model_name='functioncode',
            name='functiondef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='functioncodings', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='globalvariables', to='seeker.Gateway'),
        ),
        migrations.AlterField(
            model_name='kwic',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kwiclines', to='seeker.Basket'),
        ),
        migrations.AlterField(
            model_name='kwicfilter',
            name='kwic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kwicfilters', to='seeker.Kwic'),
        ),
        migrations.AlterField(
            model_name='kwicresult',
            name='kwic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kwicresults', to='seeker.Kwic'),
        ),
        migrations.AlterField(
            model_name='qcline',
            name='quantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qclines', to='seeker.Quantor'),
        ),
        migrations.AlterField(
            model_name='qsubcat',
            name='qcline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qsubcats', to='seeker.QCline'),
        ),
        migrations.AlterField(
            model_name='qsubinfo',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qsubinfos', to='seeker.Qsubcat'),
        ),
        migrations.AlterField(
            model_name='qsubinfo',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='browser.Text'),
        ),
        migrations.AlterField(
            model_name='quantor',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='myquantor', to='seeker.Basket'),
        ),
        migrations.AlterField(
            model_name='research',
            name='gateway',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='seeker.Gateway'),
        ),
        migrations.AlterField(
            model_name='research',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childresearch', to='seeker.ResGroup'),
        ),
        migrations.AlterField(
            model_name='research',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resgroup',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentgroup', to='seeker.ResGroup'),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='searchitems', to='seeker.Construction'),
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sharegroups', to='seeker.Research'),
        ),
        migrations.AlterField(
            model_name='vardef',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='definitionvariables', to='seeker.Gateway'),
        ),
    ]
