# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0058_auto_20190910_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='compact',
            field=models.TextField(blank=True, null=True, verbose_name='Compressed specification'),
        ),
        migrations.AddField(
            model_name='research',
            name='stype',
            field=models.CharField(choices=[('0', '----'), ('p', 'Plain'), ('s', 'Simple')], default='p', max_length=5, verbose_name='Search type'),
        ),
    ]
