# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0059_auto_20200217_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmain',
            name='fcat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Feature category'),
        ),
        migrations.AddField(
            model_name='searchmain',
            name='fval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Feaure value'),
        ),
    ]
