# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0060_auto_20210215_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='argumentdef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argumentdef_arguments', to='seeker.ArgumentDef'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='cvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvar_arguments', to='seeker.ConstructionVariable'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='dvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvar_arguments', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functionarguments', to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functiondef_arguments', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='gvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gvar_arguments', to='seeker.GlobalVariable'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_baskets', to='browser.Part'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functiondefcondition', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variablecondition', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_constructions', to='seeker.SearchMain'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_cvars', to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functiondef_cvars', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='constructionvariable',
            name='gvar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gvar_cvars', to='seeker.GlobalVariable'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='function',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeker.Function'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='functiondef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functiondeffeature', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variablefeature', to='seeker.VarDef'),
        ),
        migrations.AlterField(
            model_name='function',
            name='functiondef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functiondef_functions', to='seeker.FunctionDef'),
        ),
        migrations.AlterField(
            model_name='function',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functionparent', to='seeker.Argument'),
        ),
        migrations.AlterField(
            model_name='function',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functionroot', to='seeker.ConstructionVariable'),
        ),
        migrations.AlterField(
            model_name='function',
            name='rootcond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functioncondroot', to='seeker.Condition'),
        ),
        migrations.AlterField(
            model_name='function',
            name='rootfeat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functionfeatroot', to='seeker.Feature'),
        ),
        migrations.AlterField(
            model_name='qsubinfo',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_qsubinfos', to='browser.Text'),
        ),
        migrations.AlterField(
            model_name='research',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childresearch', to='seeker.ResGroup'),
        ),
        migrations.AlterField(
            model_name='research',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owner_researches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resgroup',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owner_resgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentgroup', to='seeker.ResGroup'),
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sharegroups', to='auth.Group'),
        ),
    ]
