# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0061_auto_20210610_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='raxis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arg_raxis', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='rcond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arg_rcond', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='rconst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arg_rconst', to='seeker.Relation'),
        ),
    ]
