# Generated by Django 2.2 on 2021-06-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0062_auto_20210610_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='raxis',
            field=models.ForeignKey(limit_choices_to={'type': 'axis'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arg_raxis', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='rcond',
            field=models.ForeignKey(limit_choices_to={'type': 'cond'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arg_rcond', to='seeker.Relation'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='rconst',
            field=models.ForeignKey(limit_choices_to={'type': 'const'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arg_rconst', to='seeker.Relation'),
        ),
    ]
