# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woorduser',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Gender'),
        ),
    ]
