# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0005_result_dontknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='created', max_length=255, verbose_name='Status'),
        ),
    ]
