# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0006_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimuli',
            name='woorduser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userstimuli', to='woord.WoordUser'),
            preserve_default=False,
        ),
    ]
