# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0007_stimuli_woorduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='woord',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='woorduser',
        ),
        migrations.AddField(
            model_name='stimuli',
            name='category',
            field=models.CharField(default='a', max_length=255, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimuli',
            name='woord',
            field=models.CharField(default='b', max_length=255, verbose_name='Woord'),
            preserve_default=False,
        ),
    ]
