# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0009_auto_20210325_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='created', max_length=255, verbose_name='Status')),
                ('woorduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woorduserqsets', to='woord.WoordUser')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qsetquestions', to='woord.Qset'),
        ),
    ]
