# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0010_auto_20210325_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qset_questionsets', to='woord.Qset')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='qset',
        ),
        migrations.AddField(
            model_name='questionset',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_questionsets', to='woord.Question'),
        ),
    ]
