# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0011_auto_20210325_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='qset',
            name='questions',
            field=models.ManyToManyField(related_name='questionsqset', through='woord.QuestionSet', to='woord.Question'),
        ),
    ]
