# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0012_qset_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
