# Generated by Django 2.2 on 2021-10-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0015_stimulus_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='woorduser',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Consent information'),
        ),
    ]
