# Generated by Django 2.2 on 2021-10-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woord', '0016_woorduser_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='questionset',
            name='status',
            field=models.CharField(default='created', max_length=255, verbose_name='Status'),
        ),
    ]
