# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-18 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='BriefEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Sub question')),
                ('help', models.CharField(max_length=255, verbose_name='Help information')),
                ('order', models.IntegerField(default=-1, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='BriefModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('short', models.CharField(max_length=255, verbose_name='Short name')),
                ('order', models.IntegerField(default=-1, verbose_name='Order')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Introduction')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BriefQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Question')),
                ('order', models.IntegerField(default=-1, verbose_name='Order')),
                ('help', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('rtype', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], default='', max_length=5, verbose_name='Response type')),
                ('ntype', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], default='', max_length=5, verbose_name='Response type')),
            ],
        ),
        migrations.CreateModel(
            name='BriefSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('order', models.IntegerField(default=-1, verbose_name='Order')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Introduction')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulesections', to='brief.BriefModule')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=100)),
                ('dutch_name', models.CharField(max_length=100)),
                ('abbr', models.CharField(default='-', max_length=20)),
                ('machine_value', models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.')),
            ],
            options={
                'ordering': ['field', 'machine_value'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='briefquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionquestions', to='brief.BriefSection'),
        ),
        migrations.AddField(
            model_name='briefentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionentries', to='brief.BriefQuestion'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectquestionanswers', to='brief.Project'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionanswers', to='brief.BriefQuestion'),
        ),
        migrations.AddField(
            model_name='answerentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryanswers', to='brief.BriefEntry'),
        ),
        migrations.AddField(
            model_name='answerentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectentryanswers', to='brief.Project'),
        ),
    ]
