# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='val', max_length=5, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='briefquestion',
            name='ntype',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Response type'),
        ),
        migrations.AlterField(
            model_name='briefquestion',
            name='rtype',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Response type'),
        ),
    ]
