# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0002_auto_20201218_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='val', max_length=5, verbose_name='Status'),
        ),
    ]
