# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0003_auto_20201218_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ptype',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='ini', max_length=5, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='briefentry',
            name='help',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help information'),
        ),
        migrations.AlterField(
            model_name='briefquestion',
            name='ntype',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], default='', max_length=5, verbose_name='Necessity type'),
        ),
        migrations.AlterField(
            model_name='briefquestion',
            name='rtype',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], default='', max_length=5, verbose_name='Response type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='val', max_length=5, verbose_name='Status'),
        ),
    ]
