# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0004_auto_20201221_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefquestion',
            name='ntype',
            field=models.CharField(blank=True, choices=[('alw', 'Always needed'), ('fir', 'Before first publication'), ('opt', 'Optional')], default='', max_length=5, verbose_name='Necessity type'),
        ),
        migrations.AlterField(
            model_name='briefquestion',
            name='rtype',
            field=models.CharField(blank=True, choices=[('mline', 'Multiple lines'), ('entri', 'Multiple objects'), ('line', 'Single line'), ('boole', 'Yes/no')], default='', max_length=5, verbose_name='Response type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ptype',
            field=models.CharField(choices=[('fir', 'First publication'), ('ini', 'Initializing'), ('sec', 'Second publication'), ('who', 'Whole Bible')], default='ini', max_length=5, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('arc', 'Archived'), ('inv', 'Invalid'), ('val', 'Valid')], default='val', max_length=5, verbose_name='Status'),
        ),
    ]
