# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-22 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0005_auto_20201222_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefquestion',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ptype',
            field=models.CharField(choices=[('fir', 'First publication'), ('ini', 'Initializing'), ('mor', 'More than two publications'), ('sec', 'Second publication')], default='ini', max_length=5, verbose_name='Progress'),
        ),
    ]
