# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-23 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0006_auto_20201222_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefmodule',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='briefquestion',
            options={'ordering': ['section', 'order']},
        ),
        migrations.AlterModelOptions(
            name='briefsection',
            options={'ordering': ['module', 'order']},
        ),
    ]
