# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0007_auto_20201223_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerentry',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionentryanswers', to='brief.BriefQuestion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ptype',
            field=models.CharField(choices=[('ini', '1 - Initializing'), ('fir', '2 - First publication'), ('sec', '3 - Second publication'), ('mor', '4 - More than two publications')], default='ini', max_length=5, verbose_name='Progress'),
        ),
    ]
