# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-26 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0008_auto_20201224_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefentry',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='answerentry',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer'),
        ),
    ]
