# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0009_auto_20201226_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product')),
                ('scripture', models.TextField(blank=True, help_text='list books, passages', null=True, verbose_name='Scripture')),
                ('format', models.CharField(blank=True, help_text='e.g. text / audio / video', max_length=255, null=True, verbose_name='Format')),
                ('media', models.TextField(blank=True, help_text='e.g. print / digital / broadcast / live performance etc', null=True, verbose_name='Media')),
                ('goal', models.TextField(blank=True, null=True, verbose_name='Goal')),
                ('audience', models.TextField(blank=True, null=True, verbose_name='Audience(s)')),
                ('timing', models.TextField(blank=True, null=True, verbose_name='Timing')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=-1, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectquestionproducts', to='brief.Project')),
            ],
        ),
    ]
