# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-26 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brief', '0011_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(default='[]', verbose_name='Information in JSON list')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(default='{}', verbose_name='Information in JSON'),
        ),
        migrations.AddField(
            model_name='history',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecthistories', to='brief.Project'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhistories', to=settings.AUTH_USER_MODEL),
        ),
    ]
